%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\git\Time-Series-Analysis\Projet\Partie3\MyTimeSeries.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/12 01:50:24

%% Import the data
[~, ~, raw] = xlsread('E:\git\Time-Series-Analysis\Projet\Partie3\MyTimeSeries.xlsx','Sheet1','I2:I127');

%% Create output variable
y = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;