%% Importing data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\git\Time-Series-Analysis\ExpSmoothing\Double\Lissage expo double.xls
%    Worksheet: Feuil1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/04 12:44:24

%% Import the data
[~, ~, raw] = xlsread('E:\git\Time-Series-Analysis\ExpSmoothing\Double\Lissage expo double.xls','Feuil1','C2:C31');

%% Create output variable
y = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;