%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\git\Time-Series-Analysis\Projet\A1.xlsx
%    Worksheet: Sheet3
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/09 23:39:05

%% Import the data
[~, ~, raw] = xlsread('E:\git\Time-Series-Analysis\Projet\A1.xlsx','Sheet3','B2:B43');

%% Create output variable
y = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;