%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Lissage Holt-Winters de la serie Consommation trimestrielle d’essences aviation V3.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/01 01:39:49

%% Import the data
[~, ~, raw0_0] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Lissage Holt-Winters de la serie Consommation trimestrielle d’essences aviation V3.xlsx','Sheet1','B2:C57');
[~, ~, raw0_1] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Lissage Holt-Winters de la serie Consommation trimestrielle d’essences aviation V3.xlsx','Sheet1','F2:F57');
raw = [raw0_0,raw0_1];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
t = data(:,1);
y = data(:,2);
I = data(1:4,3);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1;