%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\git\Time-Series-Analysis\ExpSmoothing\LES.xls
%    Worksheet: Feuil1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/04 10:32:07

%% Import the data
[~, ~, raw] = xlsread('E:\git\Time-Series-Analysis\ExpSmoothing\LES.xls','Feuil1','D2:D45');

%% Create output variable
y = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;