%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\git\Time-Series-Analysis\Décomposition saisonnière\Etude de tendance PIB Belgique&RFA.xlsx
%    Worksheet: Feuil1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/19 14:43:51

%% Import the data
[~, ~, raw0_0] = xlsread('E:\git\Time-Series-Analysis\Décomposition saisonnière\Etude de tendance PIB Belgique&RFA.xlsx','Feuil1','A7:A14');
[~, ~, raw0_1] = xlsread('E:\git\Time-Series-Analysis\Décomposition saisonnière\Etude de tendance PIB Belgique&RFA.xlsx','Feuil1','C7:C14');
raw = [raw0_0,raw0_1];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
t = data(:,1);
y = data(:,2);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1;