%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Multiplicatif\Lissage HW multip Ventes des bouteilles de champagne V2.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/01 07:15:32

%% Import the data
[~, ~, raw0_0] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Multiplicatif\Lissage HW multip Ventes des bouteilles de champagne V2.xlsx','Sheet1','A2:A106');
[~, ~, raw0_1] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Multiplicatif\Lissage HW multip Ventes des bouteilles de champagne V2.xlsx','Sheet1','C2:C106');
[~, ~, raw0_2] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt-Winters\Multiplicatif\Lissage HW multip Ventes des bouteilles de champagne V2.xlsx','Sheet1','F2:F106');
raw = [raw0_0,raw0_1,raw0_2];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
t = data(:,1);
y = data(:,2);
I = data(1:12,3);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1 raw0_2;