%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: E:\Studies\Matlab Prevision\Lissage\Lissage Gen\corre liss gene.xls
%    Worksheet: Feuil1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/02/05 19:40:49

%% Import the data
[~, ~, raw] = xlsread('E:\Studies\Matlab Prevision\Lissage\Lissage Gen\corre liss gene.xls','Feuil1','B2:B83');

%% Create output variable
y = reshape([raw{:}],size(raw));

%% Clear temporary variables
clearvars raw;