%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\YsfDS\Desktop\Projet Prevision\T1.xlsx
%    Worksheet: T5
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/04/10 22:49:59

%% Import the data
[~, ~, raw0_0] = xlsread('C:\Users\YsfDS\Desktop\Projet Prevision\T1.xlsx','T5','D2:D68');
[~, ~, raw0_1] = xlsread('C:\Users\YsfDS\Desktop\Projet Prevision\T1.xlsx','T5','G2:G68');
raw = [raw0_0,raw0_1];

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
y = data(:,1);
I = data(1:4,2);

%% Clear temporary variables
clearvars data raw raw0_0 raw0_1;