%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\YsfDS\Desktop\Lissage Holt\Lissage Holt de la serie de l''indice de salaire annuel en Italie 1962-1991.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/31 19:37:20

%% Import the data
[~, ~, raw] = xlsread('C:\Users\YsfDS\Desktop\Lissage Holt\Lissage Holt de la serie de l''indice de salaire annuel en Italie 1962-1991.xlsx','Sheet1','B2:C31');

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
t = data(:,1);
y = data(:,2);

%% Clear temporary variables
clearvars data raw;